version: '2'
services:

    nginx:
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/bots/:/etc/nginx/bots/
            - ./etc/services.conf:/etc/nginx/service.conf
            - ./www/html/:/usr/www/html/
        ports:
            - "80:80"
            - "443:443"
        env_file: .env

networks:
  default:
    external:
      name: nginx-reverse-proxy