# include this file to nginx.conf in server partition
location /shvatka/ {
    resolver 127.0.0.11 valid=30s;
    set $u_shvatka shvatka-prod;
    proxy_pass http://$u_shvatka:80;
    rewrite ^/shvatka(.*)$ $1 break;
}
